Blog_Django/news/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.sitemaps.views import sitemap
from RSS_and_SITEMAP.sitemap import NewsSitemap, StaticSitemap
# import debug_toolbar


schema_view = get_schema_view(
   openapi.Info(
      title="Library API",
      default_version='v1',
      description="online library",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="admin@mail.ru"),
      license=openapi.License(name=""),
   ),
   public=True,
   permission_classes=(permissions.AllowAny, ),
)


sitemaps = {  # список составляющих карты сайта
    'static': StaticSitemap,
    'news': NewsSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_news_board.urls')),
    path('users/', include('app_users.urls')),
    path('blog/', include('app_blog.urls')),

    path('api/', include('API_data.urls')),

    path('rss/', include('RSS_and_SITEMAP.urls')),  # лента новостей
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),  # карта сайта
    path('i18n/', include('django.conf.urls.i18n')),  # интернационализация
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema_swagger_ui'),  # спецификации API и методов

    path('blog_life/', include('blog_life.urls')),  # приложение для симуляции жизни в блоге

    # path('__debug__/', include(debug_toolbar.urls))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog_Django/news/app_news_board/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.translation import gettext_lazy as _


class News(models.Model):
    """Модель новости"""

    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('author'))
    title = models.CharField(max_length=1500, db_index=True, default=None, blank=True, null=True, verbose_name=_('title'))  # бесполезное поле, на случай если буду вводить название постов
    content = models.CharField(max_length=1500, default='', verbose_name=_('content'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('updated_at'))
    views_count = models.IntegerField(default=0, verbose_name=_('views_count'))
    is_active = models.BooleanField(default=True, verbose_name=_('is_active'))

    likes = models.ManyToManyField(User, related_name='likes', blank=True, verbose_name=_('likes'))
    saves = models.ManyToManyField(User, related_name='saves', blank=True, verbose_name=_('saves'))

    def get_absolute_url(self):
        """Метод для корректной работы карты сайта"""
        return reverse('news_detail', args=[str(self.id)])

    class Meta:
        verbose_name_plural = _('news')
        verbose_name = _('new')
        ordering = ['-id']

    def increment_view_count(self):
        """Увеличивает количество просмотрев новости на 1"""
        self.views_count += 1
        self.save()

    def total_likes(self):
        """Возвращает количество лайков"""
        return self.likes.all().count()


class Images(models.Model):
    """Модель изображений для новости"""

    news = models.ForeignKey(News, default=None, on_delete=models.CASCADE, verbose_name=_('news'))
    image = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name=_('image'))

    class Meta:
        verbose_name_plural = _('images')
        verbose_name = _('image')


class Comment(models.Model):
    """Модель комментария"""

    news = models.ForeignKey(News, on_delete=models.CASCADE, blank=True, null=True, related_name='comment_news', verbose_name=_('new'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('user'))
    text = models.CharField(max_length=1500, default=None, null=True, verbose_name=_('text'))
    image = models.ImageField(upload_to='images/comment_images/', null=True, blank=True, verbose_name=_('image'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('updated_at'))

    class Meta:
        verbose_name_plural = _('comments')
        verbose_name = _('comment')

Blog_Django/news/templates/blog/blog.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Blog
{% endblock %}



{% block menu %}
    <b>{% trans 'Blog' %}</b>
{% endblock %}



{% block content %}

<div class="board">
    <div class="profile_head" style="background-image: url('{{ user.profile.profile_head_img.url }}')">
        <div class="profile_head_img">
            {% if user.profile.profile_img %}
                <img class="profile_img" src="{{ user.profile.profile_img.url }}"/>
            {% endif %}
        </div>

        <div class="profile_head_info">
            <div class="profile_name_sub">
                <div class="profile_head_name">
                    {{ user.username }}
                </div>

                <div class="sub-section">
                    {% if request.user != user %}
                        {% include 'functions/subscribe_section.html' %}
                    {% endif %}
                </div>
            </div>

            <div class="profile_subs">
                <div class="p_sub">
                    <a href="{% url 'subscribers_list' pk=user.id %}">{% trans 'Subscribers' %}: {{ user.profile.sub_count }}</a>
                </div>
                <div class="p_subs">
                    {% if request.user == user %}
                        <a href="{% url 'subscriptions_list' %}">{% trans 'Subscriptions' %}: {{ user.profile.subs_count }}</a>
                    {% else %}
                        <b>{% trans 'Subscriptions' %}: {{ user.profile.subs_count }}</b>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="news_list">
        <ul>
            {% for post in all_posts %}
                <li>
                    <div class="news_author_img_block">
                        <a href="{% url 'user_blog' pk=user.id %}"><img class="news_author_img" src="{{ post.author.profile.profile_img.url }}"></a>
                    </div>

                    <div class="news_author_content_block">
                        <a class="news_author" href="{% url 'user_blog' pk=user.id %}">{{ post.author }}</a>
                        {{ post.created_at|date:"M d, Y" }}
                        {% if post.created_at|date:"M d, Y" != post.updated_at|date:"M d, Y" %}
                            {% trans "Edit" %}: {{ post.updated_at|date:"M d, Y" }}
                        {% endif %}
                        <br>

                        <div class="news_text_block">
                            <a class="news_text" href="{% url 'news_detail' pk=post.id %}">{{ post.content|truncatechars:100 }}</a>
                        </div>


                        <div class="news_list_info">

                            <div class="like-section">
                                {% include 'functions/like_section.html' %}
                            </div>


                            <div class="view-section">
                                <img class="news_list_info_img" src="{% static 'img/views.png' %}">{{ post.views_count }}
                            </div>
                            <div class="comment-section">
                                <img class="news_list_info_img" src="{% static 'img/comments.png' %}">{{ post.comment_news.all.count }}
                            </div>

                            {% if post.images_set.all %}
                                <div class="images-section">
                                    <img class="news_list_info_img" src="{% static 'img/news_list_img_info.png' %}">{{ post.images_set.count }}
                                </div>
                            {% endif %}


                            <div class="save-section">
                                {% include 'functions/save_section.html' %}
                            </div>

                        </div>
                    </div>
                </li>
                <br>
            {% empty %}
                {% if request.user == user %}
                    <p>{% trans "You have not published any post" %}</p>
                    <br>
                    <p><a class="add_news" href="{% url 'create' %}">{% trans "+ Add post" %}</a></p>
                {% else %}
                    <p>{{ user }} {% trans "has no posts yet" %}</p>
                {% endif %}
                <br>
            {% endfor %}
        </ul>
    </div>


    <div class="pagination">
        <span class="step-links">
            {% if all_posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ all_posts.number }} of {{ all_posts.paginator.num_pages }}.
            </span>

            {% if all_posts.has_next %}
                <a href="?page={{ all_posts.next_page_number }}">next</a>
                <a href="?page={{ all_posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock %}

Blog_Django/news/templates/blog/bookmarks.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Bookmarks
{% endblock %}




{% block menu %}
    <b>{% trans 'Bookmarks' %}</b>
{% endblock %}



{% block content %}

<div class="board">
    <div class="news_list">
        <ul>
            {% for post in saved_posts %}
                <li>
                    <div class="news_author_img_block">
                        {% if post.author.profile.profile_img %}
                            <a href="{% url 'user_blog' pk=user.id %}"><img class="news_author_img" src="{{ post.author.profile.profile_img.url }}"></a>
                        {% else %}
                            <a href="{% url 'user_blog' pk=user.id %}"><img class="news_author_img" src="{% static 'default_images/defaultuser.png' %}"></a>
                        {% endif %}
                    </div>

                    <div class="news_author_content_block">
                        <a class="news_author" href="{% url 'user_blog' pk=post.author.id %}">{{ post.author }}</a>
                        {{ post.created_at|date:"M d, Y" }}
                        {% if post.created_at|date:"M d, Y" != post.updated_at|date:"M d, Y" %}
                            {% trans "Edit" %}: {{ post.updated_at|date:"M d, Y" }}
                        {% endif %}
                        <br>

                        <div class="news_text_block">
                            <a class="news_text" href="{% url 'news_detail' pk=post.id %}">{{ post.content|truncatechars:100 }}</a>
                        </div>


                        <div class="news_list_info">
                            <div class="like-section">
                                {% include 'functions/like_section.html' %}
                            </div>


                            <div class="view-section">
                                <img class="news_list_info_img" src="{% static 'img/views.png' %}">{{ post.views_count }}
                            </div>
                            <div class="comment-section">
                                <img class="news_list_info_img" src="{% static 'img/comments.png' %}">{{ post.comment_news.all.count }}
                            </div>
                            {% if post.images_set.all %}
                                <div class="images-section">
                                    <img class="news_list_info_img" src="{% static 'img/news_list_img_info.png' %}">{{ post.images_set.count }}
                                </div>
                            {% endif %}


                            <div class="save-section">
                                {% include 'functions/save_section.html' %}
                            </div>

                        </div>
                    </div>
                </li>
                <br>
            {% empty %}
            {% endfor %}
        </ul>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock %}

Blog_Django/news/templates/blog/subscribers_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Subscribers
{% endblock %}




{% block menu %}
    <b>{% trans 'Subscribers' %}</b>
{% endblock %}



{% block content %}

<div class="board">
    <div class="target_search">
        <form action="{% url 'subscribers_list' pk=user.id %}" method="get" class="target_search_form">
            <input class="target_search_search" name="search" type="text" placeholder='{% trans "find sub..." %}'>
        </form>
    </div>

    <ul style="margin-left: 0; padding-left: 0;">
        {% for user in data %}
            <li style="list-style-type: none">
                {% if user.profile.profile_img %}
                    <div class="sub_user_img_block">
                        <a href="{% url 'user_blog' pk=user.id %}">
                            <img class="sub_user_img" src="{{ user.profile.profile_img.url }}">
                        </a>
                    </div>
                {% endif %}

                <div class="sub_user_content_block">
                    <a class="sub_user_name" href="{% url 'user_blog' user.id %}">{{ user }}</a>
                    <div class="sub_user_sub">{% include 'functions/subscribe_section.html' %}</div>
                </div>
            </li>
            <br>
        {% empty %}
        {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if data.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ data.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ data.number }} of {{ data.paginator.num_pages }}.
            </span>

            {% if all_posts.has_next %}
                <a href="?page={{ data.next_page_number }}">next</a>
                <a href="?page={{ data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}

Blog_Django/news/templates/blog/subscriptions.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Subscriptions
{% endblock %}




{% block menu %}
    <b>{% trans "Home" %}</b>
{% endblock %}

{% block content %}

<div class="board">
    <div class="news_list">
        <ul>
            {% for post in sub_posts %}
                <li>
                    {% if post.author.profile.profile_img %}
                        <div class="news_author_img_block">
                            <a href="{% url 'user_blog' pk=post.author.id %}">
                                <img class="news_author_img" src="{{ post.author.profile.profile_img.url }}">
                            </a>
                        </div>
                    {% endif %}
                    <div class="news_author_content_block">
                        {% if post.author %}
                            <a class="news_author" href="{% url 'user_blog' pk=post.author.id %}">{{ post.author }}</a>
                        {% else %}
                            <p>Anon</p>
                        {% endif %}

                        {{ post.created_at|date:"M d, Y" }}

                        {% if post.created_at|date:"M d, Y" != post.updated_at|date:"M d, Y" %}
                            {% trans "Edit:" %} {{ post.updated_at|date:"M d, Y" }}
                        {% endif %}
                        <br>
                        <div class="news_text_block">
                            <a class="news_text" href="{% url 'news_detail' pk=post.id %}">{{ post.content|truncatechars:100 }}</a>
                        </div>


                        <div class="news_list_info">
                            <div class="like-section">
                                {% include 'functions/like_section.html' %}
                            </div>


                            <div class="view-section">
                                <img class="news_list_info_img" src="{% static 'img/views.png' %}">{{ post.views_count }}
                            </div>
                            <div class="comment-section">
                                <img class="news_list_info_img" src="{% static 'img/comments.png' %}">{{ post.comment_news.all.count }}
                            </div>
                            {% if post.images_set.all %}
                                <div class="images-section">
                                    <img class="news_list_info_img" src="{% static 'img/news_list_img_info.png' %}">{{ post.images_set.count }}
                                </div>
                            {% endif %}


                            <div class="save-section">
                                {% include 'functions/save_section.html' %}
                            </div>

                        </div>
                    </div>
                </li>
                <br>
            {% empty %}
                {% trans "You don't have subscriptions" %}. <a href="{% url 'news_list' %}">Search</a> {% trans "new themes" %}
            {% endfor %}
        </ul>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock %}

Blog_Django/news/templates/blog/subscriptions_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Subscriptions
{% endblock %}




{% block menu %}
    <b>{% trans 'Subscriptions' %}</b>
{% endblock %}



{% block content %}

<div class="board">
    <div class="target_search">
        <form action="{% url 'subscriptions_list' %}" method="get" class="target_search_form">
            <input class="target_search_search" name="search" type="text" placeholder='{% trans "find sub..." %}'>
        </form>
    </div>

    <ul style="margin-left: 0; padding-left: 0;">
        {% for user in data %}
            <li style="list-style-type: none">
                {% if user.profile.profile_img %}
                    <div class="sub_user_img_block">
                        <a href="{% url 'user_blog' pk=user.id %}">
                            <img class="sub_user_img" src="{{ user.profile.profile_img.url }}">
                        </a>
                    </div>
                {% endif %}

                <div class="sub_user_content_block">
                    <a class="sub_user_name" href="{% url 'user_blog' user.id %}">{{ user }}</a>
                    <div class="sub_user_sub">{% include 'functions/subscribe_section.html' %}</div>
                </div>
            </li>
            <br>


        {% empty %}
        {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if data.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ data.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ data.number }} of {{ data.paginator.num_pages }}.
            </span>

            {% if all_posts.has_next %}
                <a href="?page={{ data.next_page_number }}">next</a>
                <a href="?page={{ data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock %}

Blog_Django/news/templates/blog/upload_file.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block title %}
    Upload file
{% endblock %}




{% block menu %}
    <b>{% trans 'Upload posts' %}</b>
{% endblock %}




{% block content %}

<div class="board">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p }}
        <button type="submit">Загрузить файл</button>
    </form>
</div>

{% endblock %}